//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prilpract
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grades
    {
        public int gradeid { get; set; }
        public Nullable<int> studentid { get; set; }
        public Nullable<int> subjectid { get; set; }
        public Nullable<decimal> grade { get; set; }
        public Nullable<System.DateTime> gradedate { get; set; }
        public Nullable<int> teacherid { get; set; }
    
        public virtual Students Students { get; set; }
        public virtual Subjects Subjects { get; set; }
        public virtual Teachers Teachers { get; set; }
    }
}
