//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prilpract
{
    using System;
    using System.Collections.Generic;
    
    public partial class Journ
    {
        public int idlog { get; set; }
        public string login { get; set; }
        public string operation { get; set; }
        public System.DateTime dateop { get; set; }
        public int userid { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
